-
  name: pb on use case of loops
  hosts: client1
  tasks:
   - name: below code for yum installation using loops
     yum:
      name: "{{ item }}"
      state: present
     loop:
      - git
      - docker
      - net-tools
      - finger

